DROP TABLE IF EXISTS ACTS_IN CASCADE;
DROP TABLE IF EXISTS DIRECTED_BY CASCADE;
DROP TABLE IF EXISTS VIDEO_LABEL CASCADE;
DROP TABLE IF EXISTS WATCH CASCADE;
DROP TABLE IF EXISTS RATING CASCADE;
DROP TABLE IF EXISTS HAS_GENRE CASCADE;
DROP TABLE IF EXISTS ROLE CASCADE;
DROP TABLE IF EXISTS PERSON CASCADE;
DROP TABLE IF EXISTS VIDEO CASCADE;
DROP TABLE IF EXISTS LABEL CASCADE;
DROP TABLE IF EXISTS GENRE CASCADE;
DROP TABLE IF EXISTS SERIES CASCADE;
DROP TABLE IF EXISTS PROFILE CASCADE;
DROP TABLE IF EXISTS CLIENT CASCADE;

CREATE TABLE CLIENT (
    email VARCHAR(255) PRIMARY KEY,
    last_name VARCHAR(100) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    address TEXT,
    subscription_end_date DATE,
    subscription_type VARCHAR(50)
);

CREATE TABLE PROFILE (
    profile_id SERIAL PRIMARY KEY,
    icon VARCHAR(255),
    name VARCHAR(100) NOT NULL,
    client_email VARCHAR(255) NOT NULL,
    FOREIGN KEY (client_email) REFERENCES CLIENT(email) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SERIES (
    series_id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL
);

CREATE TABLE GENRE (
    genre_id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE LABEL (
    label_id SERIAL PRIMARY KEY,
    title VARCHAR(100) NOT NULL
);

CREATE TABLE VIDEO (
    video_id SERIAL PRIMARY KEY,
    main_image VARCHAR(255),
    title VARCHAR(255) NOT NULL,
    duration INTEGER,
    production_year INTEGER,
    series_id INTEGER,
    season INTEGER,
    episode_number INTEGER,
    FOREIGN KEY (series_id) REFERENCES SERIES(series_id) ON DELETE CASCADE
);

CREATE TABLE PERSON (
    person_id SERIAL PRIMARY KEY,
    last_name VARCHAR(100) NOT NULL,
    first_name VARCHAR(100) NOT NULL
);

CREATE TABLE ROLE (
    role_id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    first_name VARCHAR(100),
    image VARCHAR(255)
);

CREATE TABLE HAS_GENRE (
    genre_id INTEGER,
    video_id INTEGER,
    PRIMARY KEY (genre_id, video_id),
    FOREIGN KEY (genre_id) REFERENCES GENRE(genre_id) ON DELETE CASCADE,
    FOREIGN KEY (video_id) REFERENCES VIDEO(video_id) ON DELETE CASCADE
);

CREATE TABLE RATING (
    profile_id INTEGER,
    video_id INTEGER,
    rating DECIMAL(3,1) CHECK (rating >= 0 AND rating <= 10),
    PRIMARY KEY (profile_id, video_id),
    FOREIGN KEY (profile_id) REFERENCES PROFILE(profile_id) ON DELETE CASCADE,
    FOREIGN KEY (video_id) REFERENCES VIDEO(video_id) ON DELETE CASCADE
);

CREATE TABLE WATCH (
    profile_id INTEGER,
    video_id INTEGER,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (profile_id, video_id),
    FOREIGN KEY (profile_id) REFERENCES PROFILE(profile_id) ON DELETE CASCADE,
    FOREIGN KEY (video_id) REFERENCES VIDEO(video_id) ON DELETE CASCADE
);

CREATE TABLE VIDEO_LABEL (
    profile_id INTEGER,
    label_id INTEGER,
    video_id INTEGER,
    PRIMARY KEY (profile_id, label_id, video_id),
    FOREIGN KEY (profile_id) REFERENCES PROFILE(profile_id) ON DELETE CASCADE,
    FOREIGN KEY (label_id) REFERENCES LABEL(label_id) ON DELETE CASCADE,
    FOREIGN KEY (video_id) REFERENCES VIDEO(video_id) ON DELETE CASCADE
);

CREATE TABLE DIRECTED_BY (
    video_id INTEGER,
    person_id INTEGER,
    PRIMARY KEY (video_id, person_id),
    FOREIGN KEY (video_id) REFERENCES VIDEO(video_id) ON DELETE CASCADE,
    FOREIGN KEY (person_id) REFERENCES PERSON(person_id) ON DELETE CASCADE
);

CREATE TABLE ACTS_IN (
    role_id INTEGER,
    video_id INTEGER,
    person_id INTEGER,
    PRIMARY KEY (role_id, video_id, person_id),
    FOREIGN KEY (role_id) REFERENCES ROLE(role_id) ON DELETE CASCADE,
    FOREIGN KEY (video_id) REFERENCES VIDEO(video_id) ON DELETE CASCADE,
    FOREIGN KEY (person_id) REFERENCES PERSON(person_id) ON DELETE CASCADE
);
